### ISSUE TITLE
JWTs signed with ts-nkeys are invalid for NATS server

### ISSUE THREAD

**Issue by zub0r** [nats-io/ts-nkeys#24]
Hi, I'm trying to sign [NATS JWTs](https://docs.nats.io/nats-server/configuration/securing_nats/jwt) with ts-keys, but when I use the signed JWT in NATS server configuration, the server fails to verify it and responds with 
`error parsing operator JWT: claim failed signature verification`

Is there any obvious reason for that? JWTs created with `nsc` tool are working fine.

Thanks

**Comment by zub0r** [comment]
Here are steps I used to generate the config with typescript:
https://codesandbox.io/s/nats-config-ts-71xwn

**Comment by aricart** [comment]
Actually, the code works right - the issue is that you are signing both the header and the body of the JWT. The v1 JWT only signs the body - Upcoming versions will sign both the header and body as you have done (which is correct and allows for other encodings). If you just sign the body the JWT will be correct:
```
  const header = base64url.encode(JSON.stringify(header))
  const body = base64url.encode(JSON.stringify(payload));

  const sigBase64Url = base64url.encode(keyPair.sign(Buffer.from(body)));
  const jwt = `${header}.${body}.${sigBase64Url}`;
  return jwt;
```

**Comment by aricart** [comment]
also if you are getting started with this - I recommend that you start looking at 
https://github.com/nats-io/nkeys.js
And if using nats on node.js https://github.com/nats-io/nats.js/tree/nd

**Comment by zub0r** [comment]
Thank you! 
It might be a good idea to mention in docs that your JWT implementation doesn't yet fully follow RFC7519 as claimed.
