### ISSUE TITLE
Possible unnecessary dependency

### ISSUE THREAD

**Issue by lenovouser** [nats-io/ts-nkeys#9]
I am getting this warning when installing the library:

![](https://i.lenovouser.me/bHGT6QVIA51O7xHO.jpg)

I looked at the code and it seems like the `npm` dependency isn't even required anywhere? I am just speculating, but if you were trying to force a certain npm version being installed / used on the system you'd have to use the [**`engines`**](https://docs.npmjs.com/files/package.json#engines) option:

```json
{
  "engines": {
    "npm": "^6.4.1"
  }
}
```

**Comment by Cherry** [comment]
+1. This is inflating our app and I can't see any reason for this direct dependency. Looks like someone made a typo.
